<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ESOrleansApproach.Grains</RootNamespace>
	<AssemblyName>ESOrleansApproach.Grains</AssemblyName>
  </PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\GrainInterfaces\GrainInterfaces.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	  
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="10.0.1" />
  </ItemGroup>

</Project>
