version: '3'
services:

    esorleansapproach:
        image: esorleansapproach:latest
        build:
            context: src/
            dockerfile: Dockerfile
        container_name: esorleansapproach
        environment:
            - UseInMemoryDatabase=true
            - Database__DbName=
            - Database__Host=
            - Database__Port=
            - Database__User=
            - Database__Password=
            - RabbitMQConnection__APIBaseUrl=
            - RabbitMQConnection__HostUrl=
            - RabbitMQConnection__Username=
            - RabbitMQConnection__Password=
            - RabbitMQConnection__Queue=
            - IdentityConfiguration__ClientId=
            - IdentityConfiguration__ClientSecret=
            - IdentityConfiguration__AdminCliClientSecret=
            - IdentityConfiguration__Authority=
            - OrleansConfiguration__SiloClustering__ClusterId=dev
            - OrleansConfiguration__SiloClustering__ServiceId=svc
            - OrleansConfiguration__SiloClustering__ClusteringDatabaseName=orleans.clustering.db
        ports:
            - "5001:443"
            - "5000:80"