#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /src

# Copy all src/ projects because one depend on the other
COPY [".", "."]

RUN dotnet restore "API/API.csproj"

COPY . .

WORKDIR /src/API
RUN dotnet build "API.csproj" -c Release -o /app/publish -r linux-arm64

FROM build AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish -r linux-arm64

FROM mcr.microsoft.com/dotnet/aspnet:8.0-focal-arm64v8

EXPOSE 80
EXPOSE 443
EXPOSE 30000
EXPOSE 11111

WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ESOrleansApproach.API.dll"]